import type { CheatSheetSkeleton, Resource, TranslationExample, VocabularyEntry } from './model';

export const resources: Resource[] = [
  { id: 'translation-daily', title: 'Daily translation', type: 'translation', workspace: 'Daily Norwegian', level: 'B1', category: 'Daily life', updatedAt: 'Today' },
  { id: 'news-daily', title: 'Daily News', type: 'news', workspace: 'Daily Norwegian', category: 'News', updatedAt: 'Live' },
  { id: 'vocab-transport', title: 'Transport vocabulary', type: 'vocabulary', workspace: 'Daily Norwegian', level: 'B1', category: 'Transport', updatedAt: 'Today' },
  { id: 'cheat-connectors', title: 'B2 connectors', type: 'cheatsheet', workspace: 'B2 Preparation', level: 'B2', category: 'Grammar', updatedAt: 'Today' },
  { id: 'grammar-hub', title: 'Grammar', type: 'grammar', workspace: 'B2 Preparation', category: 'Grammar', updatedAt: 'Today' },
  { id: 'grammar-subordinate', title: 'Subordinate clauses', type: 'grammar', workspace: 'B2 Preparation', level: 'B1', category: 'Sentence structure', updatedAt: 'Yesterday' },
  { id: 'tablebook-a2b1-core', title: 'A2–B1 Core Vocabulary', type: 'tablebook', workspace: 'Daily Norwegian', category: 'Reference tables', updatedAt: 'Today' },
  { id: 'tablebook-b2-toolbox', title: 'B2 Toolbox', type: 'tablebook', workspace: 'B2 Preparation', level: 'B2', category: 'Reference tables', updatedAt: 'Today' },
  { id: 'tablebook-grammar-patterns', title: 'Grammar & Word Formation', type: 'tablebook', workspace: 'B2 Preparation', level: 'B2', category: 'Grammar', updatedAt: 'Today' },
  { id: 'phrases-work', title: 'Work phrases', type: 'phrases', workspace: 'Work Norwegian', level: 'B1', category: 'Work', updatedAt: 'Yesterday' },
  { id: 'phrases-b2-oral', title: 'B2 Oral & Listening', type: 'phrases', workspace: 'B2 Preparation', level: 'B2', category: 'Oral', updatedAt: 'Today' },
  { id: 'course-hpb-07', title: 'Her på berget · Chapter 7', type: 'course', workspace: 'Her på berget', level: 'B2', category: 'Course', updatedAt: '3d' },
];

export const vocabulary: VocabularyEntry[] = [
  {
    id: 'v-forsinket',
    level: 'B1',
    category: 'Daily life',
    subcategory: 'Transport',
    theme: 'Delay',
    type: 'Adjective',
    norsk: 'forsinket',
    english: 'delayed / late',
    french: 'en retard',
    synonyms: ['sen'],
    source: 'Daily translation',
    state: 'Learning',
  },
  {
    id: 'v-komme-for-sent',
    level: 'B1',
    category: 'Daily life',
    subcategory: 'Transport',
    theme: 'Delay',
    type: 'Verb expression',
    marker: 'å',
    norsk: 'komme for sent',
    english: 'arrive late',
    french: 'arriver en retard',
    forms: 'kommer for sent · kom for sent · har kommet for sent',
    source: 'Daily translation',
    state: 'Review',
  },
  {
    id: 'v-senere',
    level: 'A2',
    category: 'Daily life',
    subcategory: 'Time',
    theme: 'Time',
    type: 'Adverb',
    norsk: 'senere',
    english: 'later',
    french: 'plus tard',
    source: 'Daily translation',
    state: 'Known',
  },
  {
    id: 'v-derimot',
    level: 'B2',
    category: 'Grammar',
    subcategory: 'Connectors',
    theme: 'Contrast',
    type: 'Connector',
    norsk: 'derimot',
    english: 'on the other hand / however',
    french: 'en revanche',
    synonyms: ['imidlertid'],
    source: 'B2 connectors',
    state: 'Learning',
  },
  {
    id: 'v-likevel',
    level: 'B2',
    category: 'Grammar',
    subcategory: 'Connectors',
    theme: 'Contrast',
    type: 'Connector',
    norsk: 'likevel',
    english: 'nevertheless / still',
    french: 'néanmoins / quand même',
    source: 'B2 connectors',
    state: 'New',
  },
  {
    id: 'v-glede-seg-til',
    level: 'B1',
    category: 'Work',
    subcategory: 'Starting a job',
    theme: 'Work',
    type: 'Verb expression',
    marker: 'å',
    norsk: 'glede seg til',
    english: 'look forward to',
    french: 'se réjouir de / avoir hâte de',
    forms: 'gleder seg til · gledet seg til · har gledet seg til',
    source: 'Work phrases',
    state: 'Review',
  },
];

export const translation: TranslationExample = {
  original: 'I might arrive a little late because the bus is delayed.',
  norsk: 'Jeg kommer kanskje litt sent fordi bussen er forsinket.',
  natural: 'Jeg blir kanskje litt forsinket fordi bussen er forsinket.',
  simpler: 'Jeg kommer litt sent. Bussen er forsinket.',
  level: 'B1',
  theme: 'Daily life · Transport · Delay',
};

export const connectorSkeleton: CheatSheetSkeleton = {
  id: 'cheat-connectors',
  title: 'B2 connectors',
  kind: 'Connector',
  level: 'B2',
  sections: [
    { id: 'function', title: 'Function', hint: 'contrast / cause / consequence / addition / example', status: 'filled', content: 'Organize connectors by rhetorical function, not alphabetically.' },
    { id: 'meaning', title: 'Meaning', hint: 'Concise EN + FR meaning', status: 'empty' },
    { id: 'position', title: 'Position', hint: 'Where can the connector appear?', status: 'empty' },
    { id: 'word-order', title: 'Word order', hint: 'Record inversion or subordinate-clause behavior', status: 'filled', content: 'Show the sentence pattern directly beside each connector.' },
    { id: 'formality', title: 'Formality', hint: 'spoken / neutral / written', status: 'empty' },
    { id: 'levels', title: 'A2 → B1 → B2 alternatives', hint: 'Build progression equivalents', status: 'empty' },
    { id: 'examples', title: 'B2 examples', hint: 'Short reusable examples', status: 'empty' },
    { id: 'errors', title: 'Common errors', hint: 'Typical learner mistakes', status: 'empty' },
    { id: 'contrast', title: 'Contrast with', hint: 'Near-synonyms and differences', status: 'empty' },
  ],
};
